// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQvDJ2MT7GCd3achOLXNHd7_k1hrzcYA',
    appId: '1:549984970718:web:b0840423af44764036df4f',
    messagingSenderId: '549984970718',
    projectId: 'sk-app-56284',
    authDomain: 'sk-app-56284.firebaseapp.com',
    storageBucket: 'sk-app-56284.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLRaQd2Xh6TP39fhHeC6c_fcLhAUo-xsU',
    appId: '1:549984970718:android:6be080020d294ab036df4f',
    messagingSenderId: '549984970718',
    projectId: 'sk-app-56284',
    storageBucket: 'sk-app-56284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhObLkbFecLpXNToxqos1zzG8lRn4Pgs',
    appId: '1:549984970718:ios:709323910f418e6136df4f',
    messagingSenderId: '549984970718',
    projectId: 'sk-app-56284',
    storageBucket: 'sk-app-56284.appspot.com',
    iosBundleId: 'com.example.skApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhObLkbFecLpXNToxqos1zzG8lRn4Pgs',
    appId: '1:549984970718:ios:397c86ee7316b53e36df4f',
    messagingSenderId: '549984970718',
    projectId: 'sk-app-56284',
    storageBucket: 'sk-app-56284.appspot.com',
    iosBundleId: 'com.example.skApp.RunnerTests',
  );
}
